import type {RebuiltContent} from '../content-types';
export const buildings=[
 {id:'lakeside',name:'Lakeside Residences',address:'18 Lake Avenue',rent:2150,beds:1,units:48,occupied:45,arrears:4200,workOrders:4,issue:'Balcony drain repairs',image:'lakeside-exterior.webp',interior:'lakeside-interior.webp',amenities:['Private balcony','In-unit laundry','Lift access']},
 {id:'parkview',name:'Parkview Court',address:'42 Garden Street',rent:2450,beds:2,units:40,occupied:38,arrears:1800,workOrders:2,issue:'Two leases awaiting signatures',image:'parkview-exterior.webp',interior:'parkview-interior.webp',amenities:['Courtyard','Bike storage','Two bedrooms']},
 {id:'millhouse',name:'Millhouse Lofts',address:'7 Mill Road',rent:1850,beds:1,units:32,occupied:28,arrears:6800,workOrders:7,issue:'Lift service backlog',image:'millhouse-exterior.webp',interior:'millhouse-interior.webp',amenities:['Exposed brick','Open-plan living','Transit nearby']},
];
export const renterLeads=[{name:'Morgan L.',budget:2300,beds:1,move:'October 1'},{name:'Lee P.',budget:2600,beds:2,move:'September 21'},{name:'Devon R.',budget:1600,beds:2,move:'October 1'}];
export const workOrders=[{id:'WO-411',issue:'Leaking kitchen supply line',unit:'Lakeside 3B',trade:'Plumbing',start:540,duration:90,travel:20,image:'inspection-leak.webp',access:'9:00–11:30 AM',estimate:650},{id:'WO-418',issue:'Damaged corridor door closer',unit:'Millhouse Level 2',trade:'Door hardware',start:680,duration:45,travel:20,image:'inspection-door.webp',access:'11:00 AM–1:00 PM',estimate:950}];
export const technicians=[{name:'Jordan',trades:['Plumbing'],busy:[{start:540,end:600,label:'Existing boiler service'}]},{name:'Casey',trades:['Plumbing','Door hardware'],busy:[]}];
export function canDispatch(order:typeof workOrders[number],tech:typeof technicians[number],assigned:{id:string;tech:string}[]){if(!tech.trades.includes(order.trade))return 'Required trade is not covered.';const start=order.start-order.travel,end=order.start+order.duration;const intervals=[...tech.busy,...assigned.filter(a=>a.tech===tech.name).map(a=>{const o=workOrders.find(w=>w.id===a.id)!;return{start:o.start-o.travel,end:o.start+o.duration,label:o.id};})];if(intervals.some(i=>start<i.end&&end>i.start))return 'Overlaps an existing assignment including travel time.';return '';}
export const leases=[{id:'LS-301',property:'Lakeside 3B',resident:'Morgan L.',rent:2150,proposed:2220,expiry:'Sep 21',day:14,comparable:[2100,2300]},{id:'LS-402',property:'Parkview 2A',resident:'Lee P.',rent:2450,proposed:2525,expiry:'Sep 29',day:22,comparable:[2400,2650]},{id:'LS-211',property:'Millhouse 1C',resident:'Sam R.',rent:1850,proposed:1905,expiry:'Oct 2',day:25,comparable:[1800,2000]}];
export const vendors=[{name:'Civic Elevator',base:7800,callout:425,parts:900,response:'4 hours',scope:'Monthly inspection',exclusions:'Parts and after-hours labor'},{name:'Metro Lift',base:10800,callout:100,parts:200,response:'2 hours',scope:'Monthly inspection + quarterly test',exclusions:'Major motor replacement'},{name:'Summit Services',base:9000,callout:280,parts:650,response:'3 hours',scope:'Monthly inspection + remote monitoring',exclusions:'Callouts and consumables'}];
export function quoteTotals(callouts:number){return vendors.map(v=>({...v,total:v.base+Math.max(0,callouts)*v.callout+v.parts})).sort((a,b)=>a.total-b.total);}
export const findings=[{id:'DF-41',title:'Supply-line leak',location:'Lakeside 3B · Kitchen',cost:650,severity:'Urgent',owner:'Casey · Plumbing',due:'Sep 8',image:'inspection-leak.webp',x:49,y:54},{id:'DF-48',title:'Door closer damage',location:'Millhouse · Level 2 corridor',cost:950,severity:'Priority',owner:'North Door Services',due:'Sep 9',image:'inspection-door.webp',x:67,y:25}];
export const statements={August:{collected:98200,repairs:8200,management:4910,utilities:6300,insurance:4200,other:17400,occupancy:'45 / 48 units'},July:{collected:96500,repairs:6200,management:4825,utilities:6100,insurance:4200,other:23275,occupancy:'44 / 48 units'}};
export const keylineContent:Record<string,RebuiltContent>={
 'keyline-lead-to-viewing':{kind:'calendar',summary:'Two renter enquiries have properties matching their stated budget and bedroom needs. One enquiry has no current match.',explanation:'The gallery compares only supplied housing requirements. Viewing holds use the same property and time-slot records shown below.',intro:'Choose an enquiry, inspect its matches, and hold a viewing.',actions:['Compared renter requirements','Matched available properties','Prepared viewing confirmations']},
 'keyline-maintenance-dispatch':{kind:'dashboard',summary:`${workOrders.length} urgent work orders need a trade-qualified technician and a clear access window.`,explanation:'The dispatch check includes travel and existing jobs. Casey can take the morning plumbing call without the overlap on Jordan’s schedule.',intro:'Review the work-order photo and itinerary before assigning a technician.',actions:['Checked open work orders','Matched technician skills','Validated dispatch travel windows']},
 'keyline-lease-renewal-flow':{kind:'record',summary:`${leases.length} leases expire within the next 30 days and need renewal proposals.`,explanation:'Current rent, comparable ranges and term length are shown for each lease. The proposed offer recalculates when rent or term changes.',intro:'Review the expiry strip and selected lease offer.',actions:['Collected expiring leases','Compared proposed rent terms','Prepared renewal review sheets']},
 'keyline-portfolio-dashboard':{kind:'dashboard',summary:'Portfolio occupancy is 92.5%. Millhouse has the highest arrears and the largest open maintenance backlog.',explanation:'The three building records reconcile to 120 units, 111 occupied units and 13 open work orders.',intro:'Select a building to inspect its operating risks.',actions:['Reconciled building occupancy','Compared arrears and work orders','Ranked property actions']},
 'keyline-listing-refresh':{kind:'record',summary:'Lakeside’s listing hides the living space and omits its strongest amenities. The proposed revision leads with the interior and specific property details.',explanation:'The advertised rent remains $2,150. Image order and copy acceptance update the preview without changing the property record.',intro:'Compare the current advert with the proposed listing.',actions:['Reviewed listing enquiry evidence','Prepared accurate listing copy','Organized property photography']},
 'keyline-vendor-quote-review':{kind:'table',summary:'The lowest quoted service fee does not always produce the lowest annual elevator cost.',explanation:'The comparison adds expected callouts and excluded parts allowances to each vendor’s annual fee.',intro:'Adjust the callout assumption to compare equivalent annual costs.',actions:['Normalized elevator quote scope','Modeled annual callout costs','Compared response commitments']},
 'keyline-inspection-pack':{kind:'record',summary:`Two photographed inspection findings carry a combined ${findings.reduce((n,f)=>n+f.cost,0).toLocaleString('en-US')} dollar repair estimate.`,explanation:'Each image is linked to its exact location, contractor and due date. Addressing a finding removes only its own estimate from the outstanding amount.',intro:'Select a photo annotation to review and resolve its finding.',actions:['Linked inspection photo findings','Estimated outstanding repair costs','Assigned accountable contractors']},
 'keyline-owner-update':{kind:'document',summary:'Lakeside collected $98,200 in August. After $41,010 in operating expenses, net operating income was $57,190.',explanation:'The statement links each expense to a supporting ledger or work-order record, and keeps capital decisions separate from operating income.',intro:'Review the period statement and supporting entries.',actions:['Reconciled Lakeside collections','Classified operating expenses','Prepared owner capital decisions']},
};
