'use client';
import {useState} from 'react';
import {Fact,Metric,Pick,Source,WidgetHeader,usd,type WidgetProps} from '../workspace-primitives';
import {leases} from './fixtures';
export function LeaseRenewalPlanner({scenario}:WidgetProps){
 const [selected,setSelected]=useState(0),[offers,setOffers]=useState<Record<string,{rent:number;term:number}>>({});const active=leases[selected],offer=offers[active.id]??{rent:active.proposed,term:12};const change=offer.rent-active.rent;
 const update=(patch:Partial<typeof offer>)=>setOffers(o=>({...o,[active.id]:{...offer,...patch}}));
 return <div className="rw kl-renewals" data-widget-state={`${selected}-${offer.rent}-${offer.term}`}><WidgetHeader title={scenario.copy.conversationTitle} eyebrow="Lease expirations · Next 30 days"/><div className="kl-expiry-strip">{leases.map((l,i)=><Pick key={l.id} primary={i===1} selected={selected===i} onClick={()=>setSelected(i)}><small>{l.expiry}</small><strong>{l.property}</strong><progress value={l.day} max="30" aria-label={`Expires in ${l.day} days`}/></Pick>)}</div><div className="kl-offer-sheet"><section><small>Renewal proposal · {active.id}</small><h4>{active.property}</h4><p>Resident: {active.resident}</p><Fact label="Current monthly rent">{usd(active.rent)}</Fact><Fact label="Comparable monthly range">{usd(active.comparable[0])}–{usd(active.comparable[1])}</Fact><p className="kl-offer-language">Proposed term: {offer.term} months at {usd(offer.rent)} per month. Total term rent: {usd(offer.rent*offer.term)}.</p></section><aside><label>Proposed monthly rent<input aria-label="Proposed monthly rent" type="number" min="1000" max="4000" step="5" value={offer.rent} onChange={e=>update({rent:Math.max(1000,Math.min(4000,Number(e.target.value)||1000))})}/></label><label>Term length<select aria-label="Lease term" value={offer.term} onChange={e=>update({term:Number(e.target.value)})}>{[6,12,18].map(n=><option key={n} value={n}>{n} months</option>)}</select></label><Metric label="Monthly change" value={usd(change)}/><Metric label="Annualized change" value={usd(change*12)} id="lease-annual-change"/></aside></div><Source>Renewal status: Draft for review · Comparable rents from September property register · Sasha Green</Source></div>;
}
LeaseRenewalPlanner.displayName='LeaseRenewalPlanner';
