'use client';
import {useState} from 'react';
import {Badge,Photo,Source,WidgetHeader,usd,type WidgetProps} from '../workspace-primitives';
import {buildings} from './fixtures';
export function ListingConversionStudio({scenario}:WidgetProps){
 const [interiorFirst,setInteriorFirst]=useState(false),[accepted,setAccepted]=useState(false);const property=buildings[0];
 return <div className="rw kl-listing" data-widget-state={`${interiorFirst}-${accepted}`}><WidgetHeader title={scenario.copy.conversationTitle} eyebrow="Listing studio · Lakeside 3B"><Badge tone={accepted&&interiorFirst?'good':'info'}>{Number(accepted)+Number(interiorFirst)} / 2 revisions accepted</Badge></WidgetHeader><div className="kl-listing-studio"><section className="kl-advert-preview"><div data-testid="listing-hero"><Photo src={`/demo-keyline/${interiorFirst?property.interior:property.image}`} alt="Lakeside listing lead photograph"/></div><div><span>{usd(property.rent)} / month</span><h4>{accepted?'Bright lakeside home with a private balcony':'Apartment available in Lakeside'}</h4><p>{accepted?'A light-filled one-bedroom home with a lake-facing living room, private balcony and in-unit laundry. Available October 1.':'One-bedroom apartment. Contact us for information.'}</p><small>{property.address} · 1 bedroom</small></div></section><aside><h4>Evidence behind the revision</h4><p>640 listing views produced 9 enquiries: 1.4%. The interior and balcony are absent from the opening photograph.</p><div className="kl-image-order"><Photo src={`/demo-keyline/${property.image}`} alt="Lakeside exterior thumbnail"/><Photo src={`/demo-keyline/${property.interior}`} alt="Lakeside interior thumbnail"/></div><button type="button" data-primary-action onClick={()=>setInteriorFirst(v=>!v)}>{interiorFirst?'Lead with exterior':'Lead with interior'}</button><div className="kl-proposed-copy"><small>Proposed headline</small><strong>Bright lakeside home with a private balcony</strong><small>Uses confirmed amenities. No rent or availability changes.</small></div><button type="button" className="rw-action" disabled={accepted} onClick={()=>setAccepted(true)}>{accepted?'Copy accepted':'Accept proposed copy'}</button></aside></div><Source>Listing LS-3B · Seven-day enquiry sample · Copy owner: Sasha Green</Source></div>;
}
ListingConversionStudio.displayName='ListingConversionStudio';
