'use client';
import {useMemo,useState} from 'react';
import {Badge,Metric,Source,WidgetHeader,usd,type WidgetProps} from '../workspace-primitives';
import {reconcileRevenue,revenueEquation,revenueTransactions,type RevenueTransaction} from './fixtures';

export function RevenueSettlementReconciler({scenario}:WidgetProps){
  const [processor,setProcessor]=useState<'All'|RevenueTransaction['processor']>('All');const [status,setStatus]=useState<'All'|RevenueTransaction['status']>('All');const [selected,setSelected]=useState('TX-8841');const [timing,setTiming]=useState<Set<string>>(new Set());const result=reconcileRevenue(timing);const transaction=revenueTransactions.find(row=>row.id===selected)!;
  const visible=useMemo(()=>revenueTransactions.filter(row=>(processor==='All'||row.processor===processor)&&(status==='All'||row.status===status)),[processor,status]);
  const markable=transaction.status==='Timing'&&!timing.has(transaction.id);
  return <div className="rw lg-revenue" data-widget-state={`${processor}-${status}-${selected}-${[...timing].join(',')}`}>
    <WidgetHeader title={scenario.copy.conversationTitle} eyebrow="Store revenue · Processor-to-bank equation"><Badge tone={result.unexplained===0?'good':'risk'}>{usd(result.unexplained)} unexplained</Badge></WidgetHeader>
    <div className="lg-revenue-equation" aria-label="Revenue settlement equation"><span><small>Captured sales</small><strong>{usd(revenueEquation.captured)}</strong></span><b>−</b><span><small>Refunds</small><strong>{usd(revenueEquation.refunds)}</strong></span><b>−</b><span><small>Fees</small><strong>{usd(revenueEquation.fees)}</strong></span><b>−</b><span><small>Chargebacks</small><strong>{usd(revenueEquation.chargebacks)}</strong></span><b>=</b><span className="is-result"><small>Expected settled</small><strong data-testid="revenue-expected">{usd(result.expected)}</strong></span></div>
    <div className="rw-metrics"><Metric label="Bank receipts" value={usd(revenueEquation.bankReceipts)}/><Metric label="Known unsettled" value={usd(revenueEquation.unsettled)}/><Metric label="Accounted timing" value={usd(result.timing)}/><Metric label="Unexplained variance" value={usd(result.unexplained)} id="revenue-unexplained"/></div>
    <div className="lg-revenue-filters"><label>Processor<select aria-label="Processor" value={processor} onChange={event=>setProcessor(event.target.value as typeof processor)}><option>All</option><option>Stripe</option><option>Shopify</option></select></label><label>Settlement status<select aria-label="Settlement status" value={status} onChange={event=>setStatus(event.target.value as typeof status)}><option>All</option><option>Timing</option><option>Unresolved</option></select></label></div>
    <div className="lg-revenue-work"><div className="rw-table-wrap"><table><thead><tr><th>Transaction</th><th>Processor</th><th>Status</th><th>Amount</th></tr></thead><tbody>{visible.map(row=><tr key={row.id} className={selected===row.id?'is-selected':''}><th scope="row"><button type="button" aria-label={`Inspect ${row.id}`} onClick={()=>setSelected(row.id)}>{row.id}<small>{row.date}</small></button></th><td>{row.processor}</td><td><Badge tone={timing.has(row.id)?'good':row.status==='Timing'?'info':'risk'}>{timing.has(row.id)?'Accounted':row.status}</Badge></td><td>{usd(row.amount)}</td></tr>)}</tbody></table>{visible.length===0&&<p className="rw-empty">No transactions match these filters.</p>}</div>
      <aside><small>{transaction.id} · {transaction.processor}</small><h4>{transaction.reason}</h4><p>{transaction.source}</p><button type="button" className="rw-action" data-primary-action disabled={!markable} aria-label={timing.has(transaction.id)?'Timing difference accounted':'Mark as supported timing difference'} onClick={()=>markable&&setTiming(current=>new Set(current).add(transaction.id))}>{timing.has(transaction.id)?'Timing accounted':transaction.status==='Timing'?'Account for timing':'Evidence required'}</button></aside></div>
    <Source>Captured sales − refunds − fees − chargebacks = expected settled revenue · Timing classifications do not change sales or cash</Source>
  </div>;
}
RevenueSettlementReconciler.displayName='RevenueSettlementReconciler';
