'use client';
import {useState} from 'react';
import {Badge,Metric,Pick,Photo,Source,WidgetHeader,type WidgetProps} from '../workspace-primitives';
import {slots,waitlist} from './fixtures';
export function AppointmentGapMatcher({scenario}:WidgetProps){
 const [slot,setSlot]=useState(0),[person,setPerson]=useState(''),[held,setHeld]=useState<Record<string,string>>({});
 const active=slots[slot];const compatible=waitlist.filter(p=>p.location===active.location&&p.service===active.service&&p.duration<=active.duration&&p.available.includes(active.id)&&!Object.values(held).includes(p.id));const chosen=compatible.find(p=>p.id===person)??compatible[0];const booked=held[active.id];
 return <div className="rw hv-appointments" data-widget-state={`${slot}-${person}-${Object.keys(held).join()}`}><WidgetHeader title={scenario.copy.conversationTitle} eyebrow="Tuesday, September 8 · Local clinic time"/><div className="hv-appointment-banner"><Photo src="/demo-harborview/reception.webp" alt="Harborview reception awaiting tomorrow’s appointments"/><div><Metric label="Appointments held" value={Object.keys(held).length} id="slots-filled"/><Metric label="Open slots" value={slots.length-Object.keys(held).length}/></div></div><div className="hv-match-columns"><section><h4>Open appointment windows</h4>{slots.map((s,i)=><Pick key={s.id} selected={slot===i} primary={i===1} onClick={()=>{setSlot(i);setPerson('');}}><strong>{s.time}</strong><span>{s.location} · {s.duration} min</span><small>{s.service}</small>{held[s.id]&&<Badge tone="good">Held</Badge>}</Pick>)}</section><section><h4>Compatible waitlist records</h4>{booked?<p className="rw-empty">This appointment is held for {booked}.</p>:compatible.length?compatible.map(p=><Pick key={p.id} selected={chosen?.id===p.id} onClick={()=>setPerson(p.id)}><strong>{p.name} · {p.id}</strong><span>{p.location} · {p.service}</span><small>Available at {active.time} · Prefers {p.preference}</small></Pick>):<p className="rw-empty">No compatible available record. Choose another slot.</p>}</section></div><footer className="hv-booking-preview"><span><small>Confirmation preview</small><p>{booked?`${booked}: appointment held for ${active.time} at ${active.location}.`:chosen?`${chosen.name}, a ${active.duration}-minute ${active.service.toLowerCase()} appointment is available tomorrow at ${active.time}, ${active.location}.`:'No notice prepared without a compatible match.'}</p></span><button type="button" className="rw-action" disabled={Boolean(booked)||!chosen} onClick={()=>{if(chosen&&!booked)setHeld(current=>({...current,[active.id]:chosen.id}));}}>{booked?'Appointment held':'Hold appointment'}</button></footer><Source>Calendar AP-901–903 · Waitlist WL-21–24 · No clinical prioritization changed</Source></div>;
}
AppointmentGapMatcher.displayName='AppointmentGapMatcher';
