'use client';
import {useState} from 'react';
import {Badge,Metric,Photo,Pick,Source,WidgetHeader,type WidgetProps} from '../workspace-primitives';
import {clinics} from './fixtures';
export function ClinicThroughputExplorer({scenario}:WidgetProps){
 const [clinic,setClinic]=useState(0),[service,setService]=useState(0),[sessions,setSessions]=useState(0);const active=clinics[clinic],capacity=active.capacity[service]+sessions*(service===0?6:4),demand=active.demand[service],gap=Math.max(0,demand-capacity);
 return <div className="rw hv-capacity" data-widget-state={`${clinic}-${service}-${sessions}`}><WidgetHeader title={scenario.copy.conversationTitle} eyebrow="Access and capacity · Next operating day"/><div className="rw-tabs">{clinics.map((c,i)=><Pick key={c.name} primary={i===1} selected={clinic===i} onClick={()=>setClinic(i)}>{c.name}</Pick>)}</div><div className="hv-throughput-layout"><Photo src="/demo-harborview/clinic-exterior.webp" alt="Harborview clinic entrance"/><section className="rw-stack"><label>Service<select aria-label="Clinic service" value={service} onChange={e=>setService(Number(e.target.value))}><option value={0}>Consultation</option><option value={1}>Ultrasound</option></select></label><label>Additional sessions <strong>{sessions} sessions · {sessions*(service===0?6:4)} added slots</strong><input aria-label="Additional sessions" type="range" min="0" max="4" value={sessions} onChange={e=>setSessions(Number(e.target.value))}/></label><Badge tone={gap?'risk':'good'}>{gap?'Demand exceeds capacity':'Demand covered'}</Badge></section></div><div className="hv-demand-chart" aria-label="Demand and appointment capacity"><div><span>Demand</span><i style={{width:`${demand/90*100}%`}}/><b>{demand} slots</b></div><div><span>Available</span><i style={{width:`${capacity/90*100}%`}}/><b>{capacity} slots</b></div></div><div className="rw-metrics"><Metric label="Uncovered demand" value={gap} id="clinic-gap"/><Metric label="Current median wait" value={`${active.wait[service]} days`}/><Metric label="Recent cancellations" value={active.cancellations[service]}/></div><p className="rw-pad">{gap?`${active.name} needs ${Math.ceil(gap/(service===0?6:4))} more session(s) for this service.`:'Added sessions cover the modeled demand. Existing wait times remain historical measures.'}</p><Source>BigQuery access report · Six consultation or four ultrasound slots per additional session</Source></div>;
}
ClinicThroughputExplorer.displayName='ClinicThroughputExplorer';
