'use client';
import {useState} from 'react';
import {Badge,Pick,Source,WidgetHeader,type WidgetProps} from '../workspace-primitives';
import {auditControls} from './fixtures';
export function ClinicalAuditReadiness({scenario}:WidgetProps){
 const [selected,setSelected]=useState(1),[replaced,setReplaced]=useState(false),[approved,setApproved]=useState(false);const active=auditControls[selected];
 return <div className="rw hv-audit" data-widget-state={`${selected}-${replaced}-${approved}`}><WidgetHeader title={scenario.copy.conversationTitle} eyebrow="Operational review · September 8"><Badge tone={replaced?'good':'risk'}>{replaced?3:2} / 3 controls evidenced</Badge></WidgetHeader><div className="hv-control-checklist">{auditControls.map((c,i)=><Pick selected={selected===i} primary={i===0} onClick={()=>setSelected(i)} key={c.name}><span className="hv-check-symbol">{i!==1||replaced?'✓':'!'}</span><strong>{c.name}</strong><Badge tone={i===1&&!replaced?'risk':'good'}>{i===1&&replaced?'Replaced':c.status}</Badge></Pick>)}</div><section className="hv-evidence-page"><div><small>Requirement {selected+1}</small><h4>{active.name}</h4><Badge>{active.owner}</Badge></div><p>{selected===1&&replaced?'August completion register accepted. All required staff training entries carry completion dates and reviewer initials.':active.evidence}</p><small>{selected===1&&replaced?'Training register TR-09 · Page 2':active.source}</small>{selected===1&&<button type="button" disabled={replaced} onClick={()=>setReplaced(true)}>{replaced?'Replacement accepted':'Accept replacement evidence'}</button>}</section><footer className="hv-cover-review"><span><strong>Cover-sheet approval</strong><small>{approved?'Cover approved':replaced?'All evidence current. Reviewer sign-off remains.':'Blocked by expired training evidence.'}</small></span><button className="rw-action" type="button" disabled={!replaced||approved} onClick={()=>setApproved(true)}>{approved?'Approved':'Approve cover sheet'}</button></footer><Source>Evidence is an operational demo record. This view does not create a downloadable audit file.</Source></div>;
}
ClinicalAuditReadiness.displayName='ClinicalAuditReadiness';
