'use client';
import {useState} from 'react';
import {Badge,Fact,Metric,Photo,Pick,Source,WidgetHeader,type WidgetProps} from '../workspace-primitives';
import {equipment} from './fixtures';
export function EquipmentServiceImpact({scenario}:WidgetProps){
 const [selected,setSelected]=useState(0),[backup,setBackup]=useState(false);const active=equipment[selected];const restored=backup&&active.id==='US-14';const impact=equipment.reduce((sum,e)=>sum+(backup&&e.id==='US-14'?0:e.slots),0);
 return <div className="rw hv-equipment" data-widget-state={`${selected}-${backup}`}><WidgetHeader title={scenario.copy.conversationTitle} eyebrow="Equipment service impact · Today"/><div className="hv-asset-cards">{equipment.map((e,i)=><Pick key={e.id} primary={i===1} selected={selected===i} onClick={()=>setSelected(i)}><Photo src={`/demo-harborview/${e.image}`} alt={`${e.name} in Harborview clinic`}/><span><strong>{e.name}</strong><small>{e.id} · {e.fault}</small></span></Pick>)}</div><div className="hv-impact-summary"><Metric label="Appointment slots exposed" value={impact} id="equipment-impact"/><div className="rw-flex">{['Room 2','Room 4','Room 5','Room 6'].map(room=><span className={`hv-room ${active.rooms.includes(room)?'selected':''}`} key={room}><strong>{room}</strong><small>{active.rooms.includes(room)?restored?'Backup active':'Selected asset affected':'Unaffected by selection'}</small></span>)}</div></div><section className="hv-service-details"><Fact label="Fault">{active.fault}</Fact><Fact label="Assigned technician">{active.technician}</Fact><Fact label="Expected restoration">{active.restore}</Fact><Fact label="Selected service impact">{restored?0:active.slots} slots</Fact><Badge tone={restored?'good':'risk'}>{restored?'Service protected':'Repair pending'}</Badge><button type="button" className="rw-action" disabled={restored||!active.backup} onClick={()=>setBackup(true)}>{restored?'Backup assigned':active.backup?'Use backup equipment':'No compatible backup'}</button></section><Source>Freshservice EQ-14 / EQ-07 · Backup inventory confirmed at 8:30 AM · Owner: Rachel Kim</Source></div>;
}
EquipmentServiceImpact.displayName='EquipmentServiceImpact';
