import type { RebuiltContent } from '../content-types';
export type Referral = { id:string; received:string; service:string; instruction:string; contact:string; missing:number|null; documents:string[] };
export const referrals:Referral[]=[
 {id:'RF-310',received:'Today · 8:05 AM',service:'Ultrasound booking',instruction:'Routine scheduling per referral',contact:'Phone · Afternoon preferred',missing:0,documents:['Signed referral form','Authorization reference','Contact confirmation']},
 {id:'RF-314',received:'Today · 8:22 AM',service:'Follow-up consultation',instruction:'Within 7 days per referring office',contact:'Email · Any time',missing:1,documents:['Signed referral form','Authorization reference','Contact confirmation']},
 {id:'RF-318',received:'Today · 8:40 AM',service:'Initial consultation',instruction:'Routine scheduling per referral',contact:'Phone · Morning preferred',missing:null,documents:['Signed referral form','Authorization reference','Contact confirmation']},
];
export const slots=[{id:'AP-901',time:'9:00 AM',location:'East clinic',service:'Consultation',duration:30},{id:'AP-902',time:'10:30 AM',location:'West clinic',service:'Consultation',duration:30},{id:'AP-903',time:'2:00 PM',location:'East clinic',service:'Ultrasound',duration:45}];
export const waitlist=[{id:'WL-21',name:'Casey M.',location:'East clinic',service:'Consultation',duration:30,available:['AP-901'],preference:'Phone'},{id:'WL-22',name:'Robin S.',location:'West clinic',service:'Consultation',duration:30,available:['AP-902'],preference:'Email'},{id:'WL-23',name:'Jamie T.',location:'East clinic',service:'Ultrasound',duration:45,available:['AP-903'],preference:'Phone'},{id:'WL-24',name:'Taylor B.',location:'West clinic',service:'Ultrasound',duration:45,available:[],preference:'Email'}];
export const coverage=[{id:'east',role:'Registered nurse',shift:'East · Tue 8 AM–4 PM',required:3,assigned:2},{id:'float',role:'Registered nurse',shift:'Float pool · Tue 8 AM–4 PM',required:1,assigned:2},{id:'west',role:'Reception',shift:'West · Tue 8 AM–4 PM',required:2,assigned:2}];
export const equipment=[{id:'US-14',name:'Ultrasound cart',fault:'Probe connector fault',rooms:['Room 4','Room 5'],slots:12,technician:'Metro Diagnostics',restore:'Today · 11:30 AM',image:'diagnostic-equipment.webp',backup:'US-08 reserve cart'},{id:'ECG-07',name:'Room 2 ECG station',fault:'Power-supply failure',rooms:['Room 2'],slots:6,technician:'North Service Team',restore:'Today · 1:00 PM',image:'exam-room.webp',backup:null}];
export const auditControls=[{name:'Equipment servicing',source:'Vanta EQ-22 · Page 4',status:'Current',evidence:'Service completion records cover all 14 diagnostic assets.',owner:'Rachel Kim'},{name:'Staff training',source:'Training register TR-08 · Page 2',status:'Expired',evidence:'The exported register is from July; the August completion record is available for replacement.',owner:'Nina Patel'},{name:'Access management',source:'Confluence OPS-12 · §3',status:'Current',evidence:'Access reviews completed August 28 with manager sign-off.',owner:'Rachel Kim'}];
export const clinics=[{name:'East clinic',capacity:[48,18],demand:[60,26],wait:[5,8],cancellations:[4,2]},{name:'West clinic',capacity:[36,12],demand:[40,15],wait:[3,6],cancellations:[2,1]}];
export const boardDecisions=[{id:'access',name:'Access recovery',actual:5,target:3,unit:'days to appointment',resource:'Two additional sessions per week',action:'Approve protected consultation sessions at East clinic.',owner:'Nina Patel',trend:'Wait time: 3 → 4 → 5 days across June, July and August.'},{id:'equipment',name:'Equipment resilience',actual:7,target:3,unit:'hours downtime / month',resource:'$8,400 reserve equipment allowance',action:'Approve the backup ultrasound service agreement and a weekly readiness check.',owner:'Rachel Kim',trend:'Downtime: 4 → 9 → 7 hours across June, July and August.'},{id:'service',name:'Service commitments',actual:92,target:95,unit:'% within service target',resource:'One coordinator half-day per week',action:'Protect the callback queue and review unreturned messages every afternoon.',owner:'Nina Patel',trend:'Within target: 89% → 91% → 92% across June, July and August.'}];
export const harborviewContent:Record<string,RebuiltContent>={
 'harborview-referral-intake':{kind:'document',summary:`${referrals.filter(r=>r.missing!==null).length} of ${referrals.length} referrals need one missing document before scheduling can proceed.`,explanation:'The queue follows the referring office’s recorded scheduling instructions. Signed forms, authorizations and contact details are checked separately.',intro:'Review each referral’s missing document and the prepared request below.',actions:['Checked referral documents','Prepared missing-file requests','Assigned scheduling follow-ups']},
 'harborview-no-show-recovery':{kind:'calendar',summary:`${slots.length} appointment gaps have compatible waitlist matches for tomorrow.`,explanation:'Matches respect clinic location, service, appointment duration and the person’s availability. Each held slot is removed from the open capacity.',intro:'Match the open appointment to an eligible waitlist record.',actions:['Matched eligible waitlist records','Checked calendar conflicts','Prepared scheduling notices']},
 'harborview-staff-rota':{kind:'table',summary:'East clinic is short one nurse for Tuesday. The float pool can cover the gap without overtime.',explanation:'The proposed move leaves the float pool at its required coverage. A reception move from West would create a new shortfall and is blocked.',intro:'Compare both shifts before accepting a coverage swap.',actions:['Compared required coverage','Checked available staff hours','Prepared covered shift swaps']},
 'harborview-equipment-ticket-triage':{kind:'dashboard',summary:`${equipment.reduce((sum,e)=>sum+e.slots,0)} appointment slots are exposed across two equipment faults.`,explanation:'The reserve ultrasound cart can protect twelve slots while the primary device is repaired. The ECG station still needs technician attention.',intro:'Inspect each asset and the rooms affected by its outage.',actions:['Linked equipment to rooms','Checked backup availability','Prepared service-impact update']},
 'harborview-compliance-evidence-pack':{kind:'document',summary:'Two of three operational controls have current evidence. The training register needs replacement before the cover sheet can be approved.',explanation:'The August register is available for review. Accepting it closes the evidence gap but still leaves the explicit reviewer approval step.',intro:'The requirements and cited replacement evidence are below.',actions:['Indexed operational evidence','Identified expired training register','Prepared cover-sheet review']},
 'harborview-operations-dashboard':{kind:'dashboard',summary:'East clinic has demand for 60 consultation slots against capacity for 48. Two extra sessions close the twelve-slot gap.',explanation:'Clinic and service filters update the demand, wait-time and cancellation evidence. Added sessions create six consultation slots or four ultrasound slots each.',intro:'Explore the capacity assumptions by clinic and service.',actions:['Reconciled clinic demand','Compared available appointments','Modeled additional service sessions']},
 'harborview-board-operations-pack':{kind:'document',summary:'Access delays, equipment downtime and callback performance require three operating decisions this month.',explanation:'The board brief connects each result to its target, trend, accountable owner and resource request.',intro:'Select a decision to review the supporting operating evidence.',actions:['Compiled operating exceptions','Linked monthly service trends','Prepared board decision requests']},
};
