'use client';
import {useState} from 'react';
import {Badge,Fact,Metric,Pick,Source,WidgetHeader,type WidgetProps} from '../workspace-primitives';
import {referrals} from './fixtures';
export function ReferralDocumentIntake({scenario}:WidgetProps){
 const [selected,setSelected]=useState(0),[received,setReceived]=useState<string[]>([]);
 const active=referrals[selected],complete=active.missing===null||received.includes(active.id);
 const incomplete=referrals.filter(r=>r.missing!==null&&!received.includes(r.id)).length;
 return <div className="rw hv-intake" data-widget-state={`${selected}-${received.join()}`}><WidgetHeader title={scenario.copy.conversationTitle} eyebrow="Referral intake · September 7"><Badge tone={incomplete?'risk':'good'}>{incomplete?'Documents outstanding':'Ready for scheduling'}</Badge></WidgetHeader><div className="hv-intake-summary"><Metric label="Received today" value={referrals.length}/><Metric label="Incomplete referrals" value={incomplete} id="referral-incomplete"/><Metric label="Ready to schedule" value={referrals.length-incomplete}/></div><div className="hv-intake-desk"><nav aria-label="Referral records">{referrals.map((r,i)=><Pick key={r.id} primary={i===1} label={`Review ${r.id}`} selected={i===selected} onClick={()=>setSelected(i)}><strong>{r.id}</strong><span>{r.service}</span><small>{r.received}</small><Badge tone={r.missing!==null&&!received.includes(r.id)?'risk':'good'}>{r.missing!==null&&!received.includes(r.id)?'One file missing':'Complete'}</Badge></Pick>)}</nav><section><div className="rw-flex"><Fact label="Recorded instruction">{active.instruction}</Fact><Fact label="Contact preference">{active.contact}</Fact></div><h4>Document checklist</h4>{active.documents.map((doc,i)=><div className="hv-document-check" key={doc}><span>{doc}</span><Badge tone={!complete&&i===active.missing?'risk':'good'}>{!complete&&i===active.missing?'Missing':'Verified'}</Badge></div>)}<div className="hv-request"><small>Prepared communication</small><p>{complete?'All required documents are present. The scheduling owner can offer a suitable appointment.':`Please send the ${active.documents[active.missing!].toLowerCase()} for ${active.id} so the scheduling team can complete this referral.`}</p></div><button className="rw-action" type="button" disabled={complete} onClick={()=>setReceived(ids=>[...ids,active.id])}>{complete?'Documents complete':'Mark document received'}</button></section></div><Source>Referral register · Outlook intake / OneDrive documents · Scheduling owner: Nina Patel</Source></div>;
}
ReferralDocumentIntake.displayName='ReferralDocumentIntake';
